# Generated by Django 4.2.16 on 2024-10-02 19:36

import cats.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='description',
            field=models.TextField(max_length=254, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='birth_date',
            field=models.DateField(help_text='Введите дату в формате дд-мм-гггг', validators=[cats.validators.cat_validate_birth_date], verbose_name='Дата рождения (дд-мм-гггг)'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.breed', verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='color',
            field=models.CharField(choices=[('Gray', 'Серый'), ('Black', 'Чёрный'), ('White', 'Белый'), ('Ginger', 'Рыжий'), ('Mixed', 'Смешанный')], max_length=16, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='description',
            field=models.TextField(max_length=254, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=100, validators=[cats.validators.cat_validate_name], verbose_name='Имя котенка'),
        ),
    ]
